name: 풀 리퀘스트
description: 풀 리퀘스트를 생성합니다
title: ""
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        프로젝트에 기여해주셔서 감사합니다!
  - type: textarea
    id: summary
    attributes:
      label: 요약
      description: 이 PR이 무엇을 하나요?
      placeholder: 변경사항에 대한 간단한 설명을 제공해주세요...
    validations:
      required: true
  - type: input
    id: related-issue
    attributes:
      label: 관련 이슈
      description: 관련 이슈 링크 (있는 경우)
      placeholder: Closes #123
  - type: checkboxes
    id: type-of-change
    attributes:
      label: 변경 유형
      description: 이 PR이 도입하는 변경 유형은 무엇인가요?
      options:
        - label: 버그 수정
        - label: 새로운 기능
        - label: 호환성 깨짐 변경
        - label: 문서 업데이트
        - label: 리팩토링
        - label: 성능 개선
        - label: 테스트 업데이트
        - label: 설정 변경
    validations:
      required: true
  - type: checkboxes
    id: testing
    attributes:
      label: 테스트
      description: 어떻게 테스트했나요?
      options:
        - label: 단위 테스트
        - label: 통합 테스트
        - label: 수동 테스트
        - label: 기타
  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷
      description: UI 변경사항이 있다면 스크린샷을 포함해주세요
      placeholder: 해당하는 경우 여기에 스크린샷을 추가해주세요...
  - type: textarea
    id: implementation
    attributes:
      label: 구현
      description: 주요 변경사항
      placeholder: 이 PR의 주요 변경사항을 설명해주세요...
  - type: textarea
    id: performance
    attributes:
      label: 성능
      description: 성능에 미치는 영향이 있나요?
      placeholder: 성능에 미치는 영향에 대해 설명해주세요...
  - type: textarea
    id: security
    attributes:
      label: 보안
      description: 보안 고려사항이 있나요?
      placeholder: 보안에 미치는 영향에 대해 설명해주세요...
  - type: checkboxes
    id: documentation
    attributes:
      label: 문서
      description: 문서 업데이트가 필요한가요?
      options:
        - label: README
        - label: API 문서
        - label: 코드 주석
        - label: 없음
  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      description: 이 PR을 제출하기 전에 다음을 확인해주세요
      options:
        - label: 코드가 스타일 가이드를 따름
        - label: 자체 검토 완료
        - label: 테스트 통과
        - label: 문서 업데이트
        - label: 민감한 데이터 포함 안함
  - type: textarea
    id: notes
    attributes:
      label: 노트
      description: 리뷰어를 위한 추가 정보
      placeholder: 리뷰어가 알아야 할 기타 컨텍스트나 정보... 