services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-local
    ports:
      - "9090:9090"
    env_file:
      - path: .env.monitoring.local
    volumes:
      - ./prometheus-local.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus-data-local:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-local
    ports:
      - "3000:3000"
    env_file:
      - path: .env.monitoring.local
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
    volumes:
      - ./data/grafana-data-local:/var/lib/grafana
    depends_on:
      - prometheus