global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    authorization:
      type: llvk
      credentials: "${LOCAL_TOKEN}"