CREATE TABLE content_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_key VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    ticket_reservation_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    original_text TEXT NULL,
    content_type VARCHAR(20) NOT NULL,
    origin_author VARCHAR(500) NULL,
    target_difficulty_levels JSON NULL,
    origin_url VARCHAR(2048) NULL,
    origin_domain VARCHAR(255) NULL,
    cover_image_url VARCHAR(2048) NULL,
    status VARCHAR(20) NOT NULL,
    progress INT NOT NULL DEFAULT 0,
    completed_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    error_message TEXT NULL,
    result_custom_content_id VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_content_requests_request_key (request_key),
    UNIQUE KEY uq_content_requests_reservation (ticket_reservation_id),
    INDEX idx_content_requests_user_status_created (user_id, status, created_at DESC),
    CONSTRAINT fk_content_requests_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_content_requests_reservation FOREIGN KEY (ticket_reservation_id) REFERENCES ticket_reservations (id)
) ENGINE=InnoDB;
