name: Run Test Code

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Docker for TestContainers
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: ./gradlew test